### ISSUE TITLE
Moodle integration?

### ISSUE THREAD

**Issue by alcarola** [jbenet/TeXchat#6]
Hi Juan,

Wow, just found TeXchat and got really impressed! 

I have set up a Moodle server for maths teaching and noticed that the standard Moodle chat is far from adequate for my purposes. Have you considered making TeXchat available as a Moodle plugin?

Greetings,
Mikael

**Comment by jbenet** [comment]
Hey Mikael!

Glad you like TeXchat.

From a quick look, it seems that Moodle is in PHP and all plugins are confined to that environment. TeXchat is written in node.js (using V8 and the node.js environment to run), so this is unfortunately not compatible.

Once [WebRTC](http://www.webrtc.org/) makes it to browsers, I plan to rewrite TeXchat to be entirely client-side javascript, but that will probably be months if not years.

You can totally use TeXchat as-is at http://texchat.juanbb.com, and make your own private rooms (let me know if it ever gives you problems). You can also download the code and set up your own instance if you have the ability and knowledge to setup a node webapp.

Cheers!
Juan

**Comment by alcarola** [comment]
Hi again, and thanks for looking into my question so quickly!

In fact, after messaging you, I started playing with setting up an own instance of TeXchat. For various reasons, I'd like a more minimalistic version of the GUI, and I would also translate it into Swedish.

The installation went fine on my laptop, but a problem with setting upp an on-line instance on my web server is that port 8080 (and almost all other ports) are closed in the firewall. Is it somehow possible to embed TeXchat into a web page served by Apache on port 80, in a setting where both Apache and TeXchat run on the same server?

If it doesn't work out for me to set up a local instance, then I'll indeed use the public one that you set up, and wait for the time to ripen for the javascript-only version. That is not a bad option either.

Greetings,
Mikael

**Comment by jbenet** [comment]
Hey again! 

Only one application can be using any given port at a time. So in your case, Apache is using it, thus node needs to use something else (8080 in this case, but this is configurable). 

One thing you can do is proxy over the traffic over port 80 to port 8080:
- Install as usual
- use mod_proxy in Apache to pass traffic to yourtexchat.com/chat to yourtexchat.com:8080/chat. Something like:
  
  ```
  <VirtualHost *:80>
    ServerName www.your-domain.com
    ProxyPreserveHost     on
    ProxyPass /chat   http://localhost:8080/chat
  </VirtualHost>
  ```
- Modify `frontend/js/main.js`:

change:

```
  TeXchat.initialize({ // config
    socketurl: 'http://' + window.location.hostname + ':8080/chat'
  });
```

to:

```
  TeXchat.initialize({ // config
    socketurl: 'http://' + window.location.hostname + '/chat'
  });
```

Although... this may not work off the bat. Websocket traffic is not normal HTTP, so there may be another directive you need to specify in Apache.  I'm sure proxying traffic from a webserver to an internal node server is doable, though. If apache doesn't cut it, you might want to check out `nginx.` And there is always `HAProxy,` which you can setup in the very front to proxy things to node or to apache accordingly.

Cheers!
Juan
